name: Nix

on:
  push:
  workflow_dispatch:

env:
  NIX_ABORT_ON_WARN: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@v8

      - name: Check flake
        run: |
          nix flake check

      - name: Test swiftly
        run: |
          nix run .#swiftly-install -- --help

      - name: Test swiftly
        run: |
          nix run .#swiftly -- --help
