name: Nix

on:
  push:
  workflow_dispatch:

env:
  NIX_ABORT_ON_WARN: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v15
        with:
          name: swift-nix
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - uses: DeterminateSystems/flake-checker-action@v9

      - name: Check flake
        run: |
          nix flake check
